apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: nash981/cassandra:latest
          ports:
            - containerPort: 9042