apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: your-docker-registry/cassandra:latest
          ports:
            - containerPort: 9042