apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: your-docker-registry/kafka:latest
          ports:
            - containerPort: 9092