apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-data-producer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-data-producer
  template:
    metadata:
      labels:
        app: stock-data-producer
    spec:
      containers:
        - name: stock-data-producer
          image: nash981/stock-data-producer:latest